version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: sensordb
    restart: unless-stopped
    environment:
      POSTGRES_DB: sensordb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka-service:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-service
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-service:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  iot-processor:
    build:
      context: .
      dockerfile: iot-processor/Dockerfile
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sensordb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-service:9092
    depends_on:
      - postgres
      - kafka-service

  iot-data-generator-service:
    build:
      context: .
      dockerfile: iot-data-generator/Dockerfile
    container_name: iot-data-generator-service
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sensordb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-service:9092
    depends_on:
      - postgres
      - kafka-service

  iot-frontend:
    build:
      context: .
      dockerfile: iot-frontend/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - iot-processor
      - iot-data-generator-service


volumes:
  postgres_data:
