name: Build & Deploy Frontend to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: iot-processing-485214
  REGION: europe-west3
  CLUSTER_NAME: iot-cluster
  CLUSTER_ZONE: europe-west3-a
  REPOSITORY: frontend
  IMAGE_NAME: iot-frontend

jobs:
  deploy:
    runs-on: ubuntu-25.10

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4


      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/997885035659/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions-gke@iot-processing-485214.iam.gserviceaccount.com

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev --quiet


      - name: Build Docker image (no cache)
        run: |
          docker build --no-cache \
            -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }}


      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials $CLUSTER_NAME \
            --zone $CLUSTER_ZONE \
            --project $PROJECT_ID


      - name: Deploy to GKE
        run: |
          kubectl set image deployment/iot-frontend \
            iot-frontend=$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }}

      - name: Verify rollout
        run: |
          kubectl rollout status deployment/iot-frontend
